# -*- coding: utf-8 -*-
"""LA project - Coffee Shope

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBELsWgaZpvd0OY-eRe5Knv6MJHGy5rp
"""

import numpy as np
from tabulate import tabulate

def display_dashboard(q, limits, costs):
    # Fixed operational constants
    prices = [5, 3, 4, 4, 3]
    labor = [4, 1, 2, 1, 0.5]
    milk = [10, 0, 5, 0, 0]
    names = ["Espresso (E)", "Drip Coffee (D)", "Specialty Tea (T)", "Pastries (P)", "Bottled (B)"]

    # Calculate totals
    total_rev, total_cost, total_labor, total_milk, total_units = 0, 0, 0, 0, 0
    table_data = []

    for i in range(5):
        rev = q[i] * prices[i]
        total_item_cost = q[i] * costs[i]
        profit = rev - total_item_cost

        # Corrected Indentation: This now aligns with the lines above it
        table_data.append([names[i], q[i], f"${costs[i]:.2f}", f"${total_item_cost:.2f}", f"${rev:.2f}", f"${profit:.2f}"])

        total_rev += rev
        total_cost += total_item_cost
        total_labor += (q[i] * labor[i])
        total_milk += (q[i] * milk[i])
        total_units += q[i]

    # Validation logic
    c_cap = total_units <= limits['cap']
    c_rev = total_rev >= limits['rev']
    c_bud = total_cost <= limits['bud']
    c_mlk = total_milk <= limits['mlk']
    c_lab = total_labor <= limits['lab']

    print("\n" + "="*95)
    print("      \t\t\tTHE DAILY GRIND: DYNAMIC OPERATIONS SIMULATOR")
    print("="*95)
    print(tabulate(table_data, headers=["Product", "Qty", "Unit Cost", "Total Cost", "Revenue", "Gross Profit"], tablefmt="fancy_grid"))

    print(f"\n\t\t\t--- KEY PERFORMANCE INDICATORS ---\n")
    print(f"Total Units:   {total_units}/{limits['cap']} " + ("✅" if c_cap else "❌ OVER CAPACITY"))
    print(f"Total Revenue: ${total_rev}/${limits['rev']} " + ("✅" if c_rev else "⚠️ BELOW TARGET"))
    print(f"Total Budget:  ${total_cost}/${limits['bud']} " + ("✅" if c_bud else "❌ OVER BUDGET"))
    print(f"Milk Usage:    {total_milk}oz/{limits['mlk']}oz " + ("✅" if c_mlk else "❌ OUT OF MILK"))
    print(f"Staff Labor:   {total_labor}min/{limits['lab']}min " + ("✅" if c_lab else "❌ OVERTIME"))
    print("="*95)

def main():
    quantities = [40, 100, 60, 80, 120]
    limits = {'rev': 1420, 'bud': 294, 'mlk': 700, 'lab': 520, 'cap': 400}
    costs = [1.0, 0.5, 0.8, 1.2, 0.5] # New dynamic costs

    while True:
        display_dashboard(quantities, limits, costs)
        print("\n1: Adjust Qty\n2: Adjust Limits\n3: Adjust Costs\n4: Reset\n5: Exit\n")
        choice = input("Enter choice: ")

        # 1: Adjust Quantities
        if choice == '1':
            print("Enter 5 new quantities (e.g., 0, 110, 0, 0, 0):")
            try:
                new_q = list(map(int, input("Enter New Values --> ").split(',')))
                if len(new_q) == 5:
                    for i in range(5):
                        if new_q[i] != 0: quantities[i] = new_q[i]
            except: print("Invalid Input.")

        # 2: Adjust Limits
        elif choice == '2':
            print("Enter new limits for: Rev, Bud, Milk, Lab, Cap (e.g., 1500, 0, 0, 0, 0):")
            try:
                new_l = list(map(int, input("Enter New Values --> ").split(',')))
                if len(new_l) == 5:
                    keys = ['rev', 'bud', 'mlk', 'lab', 'cap']
                    for i in range(5):
                        if new_l[i] != 0: limits[keys[i]] = new_l[i]
            except: print("Invalid Input.")

        # 3: Adjust Costs
        elif choice == '3':
            print("Enter 5 new unit costs (e.g., 1.2, 0, 0.9, 0, 0):")
            try:
                new_c = list(map(float, input("-> ").split(',')))
                if len(new_c) == 5:
                    for i in range(5):
                        if new_c[i] != 0: costs[i] = new_c[i]
            except: print("Invalid Input.")

        # 4: Reset
        elif choice == '4':
            quantities = [40, 100, 60, 80, 120]
            limits = {'rev': 1420, 'bud': 294, 'mlk': 700, 'lab': 520, 'cap': 400}
            costs = [1.0, 0.5, 0.8, 1.2, 0.5]

        # 5: Exit
        elif choice == '5': break

if __name__ == "__main__":
    main()